### ISSUE TITLE
last line not detected if no new line ending exist

### ISSUE THREAD

**Issue by fa1rid** [Cynosureprime/rling#10]
The last line of [remfil1 remfile2 ...] is not being detected if the line doesn't have new line ending like \n 

But input last-line is detected.

I noticed that cat command also doesn't output last line if it has no newline ending.

How does this behavior work in linux systems?

**Comment by Waffle2** [comment]
`echo -n 999999999 >rem1
$./rling 1bs.txt out rem1
Reading "1bs.txt"...9888888890 bytes total in 2.3918 seconds
Counting lines...Found 1000000000 lines in 3.0224 seconds
Optimal HashPrime is 1610612741 
Estimated memory required: 38,878,648,450 (36.21Gbytes)
Processing input list... 1000000000 unique (0 duplicate lines) in 17.8593 seconds
Occupancy is 744971109/1610612741 46.2539%, Maxdepth=9
Removing from "rem1"... 1 removed

1 total line removed in 0.0008 seconds`

Seems to work under linux.  But it does not work under windows.

Good catch! and changes pushed.
