### ISSUE TITLE
could you add character / regex filtering?

### ISSUE THREAD

**Issue by jvaneck** [Cynosureprime/rling#15]
This is a great app. Keep it up. 

Since you mentioned you are interested in suggestions....would it be possible to add a character mask to the keep or delete lines?

examples: 
1- remove all spaces from 40GB file A
2- remove all spaces from 40GB file A that has matches in file B
3- only remove (or keep) lines that are in a certain character list 
4- ability to remove non english characters
5- ability to remove specified characters, then remove duplicates that the new list might have created

**Comment by Waffle2** [comment]
Let's try to take these in order:

1.  This would *appear* to be an application of sed 's/ //g', no?
2.  I'm uncertain exactly what you mean here.
3.  How would the character list be specified, please?  UTF-8 gets very large, very fast.
4. This would *appear* to be an application of sed, again, but if you really mean "non english", then given UTF-18, I'm not certain that this can be expressed easily.  There are "english" characters in other utf-8 ranges.  If you mean ASCII-7, then it's a *bit* easier (can be done with sed or grep), but parsing UTF-8 is really, really hard.  I've been looking at it for years, for the potential application of rules for MDXfind on UTF-8 characters, and I become quite insane after a few weeks of looking at the variations.
5. How would the character(s) be specified, please?

This kind of thing gets really hard, really fast - and what doesn't get fast is the performance.  Just a simple case like 5, could expand the processing time exponentially (like taking a 2 minute job and making it a 2 day to 3 week job).  This needs to be looked at carefully, and my experience with getpass show that users can easily become overwhelmed with options.  Near as I can tell, none of these new functions have an easily documented "here's what I mean" description.

**Comment by jvaneck** [comment]
1. I agree, it would be an application of sed but since your application is so fast, I just thought it might be worth asking. 
for 2-5: Since your code works so well, it would be really great to be able to do more at the speed you've accomplished. Sorry if my suggestions don't make a lot of sense. 

Further thoughts on #3 and #5; in hashcat you can run a mask attack, similar to this: -1 ?dabcdef -2 ?l?u ?1?1?2?2?2?2?2

if someone was able to use the performance of your application and filter words from a file that don't match a certain mask, it might prove to be very useful

Please close this if these ideas aren't in the right direction of suggestions that you're looking for

**Comment by Waffle2** [comment]
I understand, but what I'm looking for, if you want new features, is a fully thought out interface.  This isn't an "attack" of any kind, so terminology like "mask attack" has no bearing on what this does.

Ideally, you would supply an example command line, and a sample of input what you would like to see for output. 

Better yet would be an explanation of _why_ this would be a useful improvement.  What problem, specifically, does it solve?

**Comment by Waffle2** [comment]
I understand, but what I'm looking for, if you want new features, is a fully thought out interface.  This isn't an "attack" of any kind, so terminology like "mask attack" has no bearing on what this does.

Ideally, you would supply an example command line, and a sample of input what you would like to see for output. 

Better yet would be an explanation of _why_ this would be a useful improvement.  What problem, specifically, does it solve?
