### ISSUE TITLE
no target overwrites source

### ISSUE THREAD

**Issue by Shooter3k** [Cynosureprime/rling#23]
If you run this command in Windows, it overwrites the last file in the directory you are trying to check your source against. RIP to my data

rling C:\source.txt C:/test2/*

Example: 
C:\test2>dir
 Volume in drive C is 465GB
 Volume Serial Number is 
 Directory of C:\test2
06/04/2021  04:37 PM    <DIR>          .
06/04/2021  04:37 PM    <DIR>          ..
06/04/2021  04:37 PM                 0 test1.txt
06/04/2021  04:36 PM                 0 test2.txt
06/04/2021  04:36 PM                 0 test3.txt
               3 File(s)              0 bytes
               2 Dir(s)  91,923,488,768 bytes free

C:\>**rling C:\source.txt C:/test2/***
Reading "C:\source.txt"...0 bytes total in 0.0075 seconds
Counting lines...Found 0 lines in 0.0013 seconds
Optimal HashPrime is 1543
Estimated memory required: 104,869,976 (100.01Mbytes)
Processing input list... 0 unique (0 duplicate lines) in 0.0009 seconds
Occupancy is 0/1543 0.0000%, Maxdepth=0
Removing from "C:/test2/test2.txt"... 0 removed

0 total lines removed in 0.0031 seconds
Writing to "**C:/test2/test1.txt**"

Wrote 0 lines in 0.0009 seconds
Total runtime 0.0201 seconds

**Comment by Waffle2** [comment]
This is, in fact, how it is intended to work, and I can see no way to fix the user behavior to prevent it.  I'm happy to listen to suggestions, though.

**Comment by Shooter3k** [comment]
ok, I'll bite. I can't get my head around how this could be intended. 


C:\test1>dir L:\test2
 Volume in drive L has no label.
 Volume Serial Number is CA00

 Directory of L:\test2

06/04/2021  05:43 PM    <DIR>          .
06/04/2021  05:43 PM    <DIR>          ..
06/04/2021  05:43 PM                 0 test2.log
06/04/2021  04:47 PM            95,658 test3.log
06/04/2021  04:51 PM            52,612 test4.log
06/04/2021  05:40 PM                 5 test5.log
               4 File(s)        148,275 bytes
               2 Dir(s)  1,260,088,832,000 bytes free

C:\test1>rling "test1.txt" l:/test2/*
Reading "test1.txt"...4 bytes total in 0.0021 seconds
Counting lines...Found 1 line in 0.0012 seconds
Optimal HashPrime is 1543
Estimated memory required: 104,869,996 (100.01Mbytes)
Processing input list... 1 unique (0 duplicate lines) in 0.0025 seconds
Occupancy is 1/1543 0.0648%, Maxdepth=0
Removing from "l:/test2/test3.log"... 0 removed
Removing from "l:/test2/test4.log"... 0 removed
Removing from "l:/test2/test5.log"... 1 removed

1 total line removed in 0.0094 seconds
Writing to "l:/test2/test2.log"

Wrote 0 lines in 0.0013 seconds
Total runtime 0.0214 seconds

C:\test1>


Thoughts: 
1) why did it pick the first file to overwrite? How does it know which one to pick?
2) why is it comparing all the files in the directory and overwriting the first file? Why is it taking both actions
3) If this is "intended", could a parameter be added so that when the second parameter is a directory, it doesn't compare against the directory and pick a file to overwrite that already exists? This should be default behavior IMO

**Comment by Waffle2** [comment]
rling doesn't analyze the filename(s) you specify, and does not try to figure out what you meant.  It depends on the shell to do that (rling is most often used on unix, not Windows, and follows the conventions there).  By the time it gets to the main() function, all of the filenames have been expanded into a list of names - there is no information left for it to look at.  rling foo bar *.txt ends up as "foo" "bar" "file1.txt" "file2.txt" "file3.txt"... inside of the program.

1.  It did not pick the first file.  You told it to use the first file.
2. It isn't comparing all of the files in the directory, and overwriting the first file.  It uses the first file as the input, and the second as the output, and all of the rest of the files are used as "remove" files.  It never (ever) sees that you put a directory name there.
3. The second parameter, from your point of view, is simply not visible to rling.  The shell hides it from me, so I don't have to do filename globbing.  As far as default behavior goes - it is doing the right thing.  That you did not place an output file is the root of the problem.

rling infile outfile [remfiles...] is how it is documented to be used, and how it should be used.  You can always "force" this behavior as well -  use stdin and stdout as the names for the input and output files, and re-direct the input and output as you see best (though this is likely to be somewhat slower on Windows, as Windows treats file I/O differently that stdin/stdout.

I suppose I could never default, and force "--infile foo --outfile bar", and reject any other syntax - but that would certainly annoy other users, and it gets away from the original "rli" program, which depends on this behavior too.  

So, please always use rling infile outfile.  Add more files if you like - but always use infile outfile....
