### ISSUE TITLE
Inconsistent sorting order compared to sort

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [Cynosureprime/rling#25]
When sorting a file, rling will not sort a file in the same order as sort will.
Why is this bad? Because join relies on a sorted order which means that join will give the following error:

Full file (already sorted with rling):
[1937.400.txt](https://github.com/Cynosureprime/rling/files/6887818/1937.400.txt)

`join: 1937.400.txt:13: is not sorted: $P$B..FxyUFO323/k/HiAafqMdkugSBWW0`

```
root@localhost:~# sort 1937.400.txt > 1937.400.txt.sort
root@localhost:~# rling 1937.400.txt 1937.400.txt.rli
root@localhost:~# md5sum 1937.400.txt
be29561593c62e683eee83c34d82f52c  1937.400.txt
root@localhost:~# md5sum 1937.400.txt.rli
be29561593c62e683eee83c34d82f52c  1937.400.txt.rli
root@localhost:~# md5sum 1937.400.txt.sort
5eb25f288c391d3093579303b62ea52a  1937.400.txt.sort

```

```
root@localhost:~# head 1937.400.txt.sort
$P$B000MgIAmZghR/1sLu9q54U61F5XU81
$P$B000zD6nvS4mSj4wMkLiwpGVgXC6.U/
$P$B002G0S6AMtfD.y6BnVI2Ln7lDqzln/
$P$B003q.yp2kebXiHl7i7hcy2ctkJHyQ0
$P$B004MP8UOgD2bMZ4bTvTGA/BInzF/v1
$P$B004OXy6b77AAQV3uadGXzY.1Z49GV.
$P$B008ZdffTYmhFMQhPcCPUREFRZjIIK1
$P$B00ASyqiwTeDr6TU6HEKPLXFW0lVmk1
$P$B00athv2hWSw63fnrZc7WNnrTh6QKq0
$P$B00/bWdiOZ9Dw07JVu/.GkCBTXXeMT0
```

```
root@localhost:~# head 1937.400.txt.rli
$P$B../ahBhMW1XFRFO8dfdIHhsATdk4s0
$P$B..0xFcETv3dQT3ZPIXUQCbMua8iOi1
$P$B..171jxu.vh6iyd.POuwP3amhizEx.
$P$B..40gqI9QEFGQKeaRtakBwl18nKbp1
$P$B..4bg/VhcQQwXCvKOQryDgtslwErH.
$P$B..5q50MxJCqYDX3Co57AcgVXpSfKK.
$P$B..6oWKqQMMxFHENbr4WpOiRVnh7PX.
$P$B..7SZtxsjbJZK6kTVu2q3WLQ8vDRD1
$P$B..8dgBTXknvP6GXilSgZq11rkCRpa.
$P$B..9AuhMD6TQFK4oXb6nEu30M2JRb71
```

**Comment by TheWorkingDeveloper** [comment]
edit: updated with example.

**Comment by Waffle2** [comment]
rling uses C lexical order.  Setting LC_ALL=C in the environment for sort will yield exactly the right output for both.  If you want a different order (like the multitude of options available in sort) a separate pass will be required. 
Of course, I'm not opposed if you want to add the various sort options to rling - feel free!

**Comment by TheWorkingDeveloper** [comment]
can confirm that prefixing LC_ALL=C to the join command does indeed work.
