### ISSUE TITLE
Slow line counting in -f

### ISSUE THREAD

**Issue by PenguinKeeper7** [Cynosureprime/rling#27]
This was brought up a while ago, but doesn't seem to be fixed. There seems to be a large discrepancy between counting lines in "normal mode" with no arguments and -f. No other mode seems to have this issue. I'm running Windows and hops could recreate it on Linux, although rling was 3x faster than wc -l for him
```
./rling -fs hibpv1.txt output2.txt
Counting lines...Found 320294410 lines in 285.6787 seconds

 ./rling hibpv1.txt output2.txt
Counting lines...Found 320294410 lines in 12.4484 seconds

$ time wc -l hibpv1.txt
320294410 hibpv1.txt

real    0m3.998s
user    0m2.250s
sys     0m1.749s
```

**Comment by Waffle2** [comment]
Rling doesn't just count lines, of course.  It does a fair amount of work.  -f creates virtual memory-type work files, and will always be slower than using real memory.

If you find a way to make disk as fast as memory, please feel free to submit a patch :-)

Likewise, if you can find a way for wc to do the same operations as rling, in anything approaching the time rling takes, I'll take those patches too!

**Comment by PenguinKeeper7** [comment]
Could the text be changed to "Counting lines and creating files" or something like that? Seems like a UX bug, in that case

**Comment by Waffle2** [comment]
This happens already if the input file is not a regular file (for example, if you are using rling as part of a pipeline operation).  If you would like to do it for regular files as well, the right place would be around line 2525, just after the "unlink(DBNAME);"

**Comment by PenguinKeeper7** [comment]
Sure, but why not do it for regular files as well? Wouldn't it label the operation better than just "counting lines"?

**Comment by roycewilliams** [comment]
My $0.02. I think 'Counting lines' has the correct level of precision and should not be changed. If users don't initially grasp that using -f will make things slower, there's only so much educational "water" that the short-form help and UI feedback can carry, before it gets too busy. I'd be OK with trying to explain it in a man page (which, IIRC, is only me to spearhead), but I don't think the text should be changed.

**Comment by Waffle2** [comment]
I don't think it should be changed, either - but that's the joy of code.  If you don't like it - fix it how you like!   Of course it's doing a lot more than "counting lines", but do I really need to explain how line termination works, and why CRLF is broken?  I doubt it.

There are still some changes that I *would* like to make, which I hope to get to soon (in particular the non-deterministic way duplicate lines are handled, due to the variability of cores).  Doesn't change the result, but it would offer more comfort for those unfamiliar with parallel processing variability.

**Comment by PenguinKeeper7** [comment]
The question is no longer about speed. Of course it'll be slower, I just mis-understood it as a bug, due to the label only saying "Counting lines". Something that obviously shouldn't be influenced by -f, when in reality, it was creating temp files and such, which obviously _should_ affect performance, leading me and hops down the wrong rabbit hole for a while and scratching our heads
