### ISSUE TITLE
Possible BUG

### ISSUE THREAD

**Issue by JustGuardian** [Cynosureprime/rling#33]
rling.exe 'C:\Users\*****\Downloads\HashesOrgLeaks.txt' 'D:\Vault\Warehouse\Wordlists\HashesOrgLeaks-sorted.lst'
Reading "C:\Users\*****\Downloads\HashesOrgLeaks.txt"...26507106430 bytes total in 141.8828 seconds
Counting lines...    Final Sortlist shrink failed
This means we read all 26507106430 bytes of the input file,
and were able to create the sortlist for all 2431652963 lines we found
Likely, there is a bug in the program.

If you need a log file to find the actual log, please tell me where to find it and I would send it asap.

------EDIT------
Forgot to mention that the file a 24,6 GB (26.507.108.352 byte) Wordlist and I have 16GB of 2666MHz ram

**Comment by Waffle2** [comment]
That would be why.  Windows does not handle memory particularly well.  Increase the amount of RAM in your system, or split the file so it is smaller.

**Comment by JustGuardian** [comment]
I recreated the file and re-ran rling and it worked. What could it be?
Also i notice that with large file the normal mode takes a very long time, while the file mode (-f) does the sort and dedupe very fast. What can be the problem?

**Comment by Waffle2** [comment]
Windows does not handle memory particularly well.  Increase the amount of RAM in your system, or split the file so it is smaller.  -f is a workaround for "not enough memory".  Add memory to your system.
