### ISSUE TITLE
Rling -2 cuts off after exactly 25MiB without errors, destroying the file

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [Cynosureprime/rling#37]
I have two separate lists that contain sorted data. When sorting them the program completes without errors, but at the end of the process exited without error after 25600KiB exactly, or 25MiB

```
.\rling.exe -2 .\412.left.sorted .\412.left.sorted
Estimated memory required: 52,429,024 (50.00Mbytes)
Allocated in 0.0197 seconds
Start processing input ".\412.left.sorted"
Input file ".\412.left.sorted" complete. 327680 unique (0 dup lines) read. 0.0402 seconds elapsed
327,680 total lines written, 0 lines removed
Total runtime 0.0692 seconds
```

```
.\rling.exe -2 .\412.left.sorted .\412.left.sorted -M 10M
Memory for cache set to 10485760 bytes (was 52428800)
Estimated memory required: 10,485,984 (10.00Mbytes)
Allocated in 0.0053 seconds
Start processing input ".\412.left.sorted"
Input file ".\412.left.sorted" complete. 65536 unique (0 dup lines) read. 0.0061 seconds elapsed
65,536 total lines written, 0 lines removed
Total runtime 0.0218 seconds
```
Further proving the cause - memory allocation

The output appears normal, except that the file does not contain 327,680 lines but 1.8 Million sorted and deduplicated.

**Comment by Waffle2** [comment]
I don't think you meant to do that.

rling input output [remfil1 remfile2 ...]

In your case, you are reading 412.left.sorted, and putting the output to 412.left.sorted.

**Comment by PenguinKeeper7** [comment]
In-place file overwriting works for the other modes, just not -2 hence the issue

**Comment by roycewilliams** [comment]
Ah, so trying to combine -2 and in-place should produce a "you can't do that" message?
