### ISSUE TITLE
My system running into memory limit if using -q w

### ISSUE THREAD

**Issue by AlQubeAl** [Cynosureprime/rling#39]
Hello,

i have a 25gb file and only 16gb ram, but i want to deduplicate it and sort it by frequency. I am using `rling.exe -f -q w 25gbinputfile.txt output.txt` but if i am using it like this i always run into memory limit. If i just run rling without -q w everything works fine. Is it somehow possilbe, to sort the inputfile by frequency, even if the inputfile is bigger than the available ram?

thank you

**Comment by Waffle2** [comment]
No.  Get more ram - it's cheap.

**Comment by roycewilliams** [comment]
One potential workaround is to split the file into multiple chunks, do a frequency count on each file, and then merge the frequency counts. Depending on your duplication density, this can work. If the frequency-count data is sorted by word, not by frequency count, merging them can be done with almost no RAM at all.

**Comment by Waffle2** [comment]
A better solution is to rent a vps.  AWS charges about $0.37 per hour for a 32G machine (and you can get much, much more memory).   In a few minutes, you could have the data set up exactly how you like it, with the change that fell under your car seat :-)
