### ISSUE TITLE
Cannot mmap "inputfile.txt" Resource temporarily unavailable

### ISSUE THREAD

**Issue by AlQubeAl** [Cynosureprime/rling#40]
Hello,

i am trying to deduplicate a 82GB file, but i am getting the error message:
Cannot mmap "inputfile.txt"
inputfile.txt Resource temporarily unavailable

Command i use `rling.exe -f "inputfile.txt" "outputfile.txt"`

**Comment by Waffle2** [comment]
Most likely you do not have enough memory to process this.  Break the file into smaller chunks to deduplicate, then combine to confirm.

This can also happen if you don't have sufficient permissions for the file to be mmap'ed.

**Comment by AlQubeAl** [comment]
> Most likely you do not have enough memory to process this
that is definitely the case, but i thought that's why the -f parameter exists. 

If i split now the 82GB file in 1GB chunks, what would the rling command look like, to deduplicate all lines from all chunks?

Thank you

**Comment by Waffle2** [comment]
I don't have an 82G file handy, but to give you an idea, here is some numbers on a 13G one, containing 1,270,725,408 lines.
On my machine, it took 4.37 seconds to read the file, 8.41 seconds to count the lines, 51.30 seconds to process and remove dupes, and 72.74 seconds to write the file, and used 44G of memory with the default options. 

rling -f in out took a lot longer (as expected), but used only about 120M of memory.

But you can be creative... let's say your files are called split01 through split82.  You can process the files like this:

rling split01 out/split01 split0[2-9] split[1-8]*
rling split02 out/split02 out/* split0[3-9] split[1-8]*
rling split03 out/split03 out/* split0[4-9] split[1-8]*
...
rling split82 out/split82 out/* 

This will leave you 82 files in the "out" directory that are unique.  You can recombine them, but you will end up with
the same issue(s) in the future, so I would not.  Large single files are hard to handle.
