### ISSUE TITLE
Missing License information

### ISSUE THREAD

**Issue by sbrun** [Cynosureprime/rling#41]
Hello,

I did not find information about the license of this project. It would be nice if you could clarify that, whatever license you choose.
So we would know for sure what to do or not to do with the code.

We would like to package this for Kali Linux and we need to know the license.

Many thanks

**Comment by blazer2x** [comment]
MIT license has been added

**Comment by roycewilliams** [comment]
@sbrun Now that the license thing is clarified ... when will rling land in Kali? Just curious!
